get    'sections',            :to => 'project_sections#index'
get    'sections/new',        :to => 'project_sections#new'
post   'sections/create',     :to => 'project_sections#create'
post   'sections/:id/edit',   :to => 'project_sections#edit'
patch  'sections/:id/update', :to => 'project_sections#update'
delete 'sections/:id',        :to => 'project_sections#destroy'
get    'section/*section',    :to => 'sections#index'
get    'project/*section',    :to => 'projects#show'
